# Generated by Django 4.2.6 on 2024-01-29 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='comm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='emp',
            name='deptno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dept'),
        ),
    ]
